url: https://evanhahn.com
name: Evan Hahn
description: I'm a programmer who loves a good panini
timezone: America/Chicago
future: false
lsi: false
permalink: :title
markdown: kramdown
paginate: 5
plugins: [jekyll-paginate]
