url: http://evanhahn.com
name: Evan Hahn
description: I'm a talking slime ball who can write code
timezone: America/Los_Angeles
future: false
lsi: false
permalink: :title
markdown: redcarpet
paginate: 5
gems: [jekyll-paginate]
